version: 2

run:
  timeout: 5m
  tests: true
  skip-dirs:
    - "vendor"
    - "migrations"

linters:
  enable:
    - govet           # проверка потенциальных ошибок
    - staticcheck     # расширенные проверки кода
    - errcheck        # проверка необработанных ошибок
    - gocyclo         # сложность функций
    - unparam         # неиспользуемые параметры функций
    - ineffassign     # неэффективные присвоения

formatters:
  enable:
    - gofmt           # форматирование кода
    - goimports       # сортировка импортов

issues:
  exclude-use-default: false
  max-issues-per-linter: 50
  max-same-issues: 5
  exclude-rules:
    - path: "_test.go"
      linters:
        - gocyclo
        - revive